version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:v1
    ports:
      - "80:80"
    volumes:
      - /home/prashanth/FYP/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/prashanth/FYP/backend/media:/app/media

  backend:
    container_name: backend
    build: ./backend
    image: backend:v1
    volumes:
      - /home/prashanth/FYP/backend/fyp/settings/prod.py:/app/fyp/settings/prod.py
      - /home/prashanth/FYP/backend/media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=fyp.settings.prod