version: '3'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      platforms:
        - ${FYP_PLATFORM-linux/arm64}
    image: prashanth45/fyp:frontendv1
    ports:
      - "80:80"
    environment:
      - FYP_SITE_DOMAIN=${FYP_SITE_DOMAIN}
      - FYP_BACKEND_HOST=${FYP_BACKEND_HOST}
    volumes:
      # - /home/prashanth/FYP/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${MEDIA_PATH}:/app/media
    depends_on:
      - backend
    #restart: always

  backend:
    container_name: backend
    build: 
      context: ./backend
      platforms:
        - ${FYP_PLATFORM-linux/arm64}
    image: prashanth45/fyp:backendv1
    ports:
      - "8000:8000"
    volumes:
      #- /home/prashanth/FYP/backend/fyp/settings/prod.py:/app/fyp/settings/prod.py
        - ${FIREBASE_CONF_PATH}:${GOOGLE_APPLICATION_CREDENTIALS}
        - ${MEDIA_PATH}:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=fyp.settings.prod
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FYP_SITE_DOMAIN=${FYP_SITE_DOMAIN}
      - FYP_SITE_PORT=${FYP_SITE_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    #restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      # MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: