version: '3'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      platforms:
        - ${FYP_PLATFORM-linux/arm64}
    image: prashanth45/fyp:frontend${FYP_VERSION}
    ports:
      - "80:80"
    environment:
      - FYP_NGINX_SERVERS=${FYP_NGINX_SERVERS}
      - FYP_BACKEND_HOST=${FYP_BACKEND_HOST}
    volumes:
      # - /home/prashanth/FYP/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${MEDIA_PATH}:/app/media
    depends_on:
      - backend
    #restart: always

  api-backend:
    container_name: api-backend
    build:
      context: ./backend
      dockerfile: DockerfileNginx
      platforms:
          - ${FYP_PLATFORM-linux/arm64}
    image: prashanth45/fyp:api-backend${FYP_VERSION}

  backend:
    container_name: backend
    build: 
      context: ./backend
      platforms:
        - ${FYP_PLATFORM-linux/arm64}
    image: prashanth45/fyp:backend${FYP_VERSION}
    ports:
      - "8002:8000"
    volumes:
      #- /home/prashanth/FYP/backend/fyp/settings/prod.py:/app/fyp/settings/prod.py
        - ${FIREBASE_CONF_PATH}:${GOOGLE_APPLICATION_CREDENTIALS}
        - ${MEDIA_PATH}:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=fyp.settings.prod
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FYP_SITE_DOMAIN=${FYP_SITE_DOMAIN}
      - FYP_SITE_NAME=${FYP_SITE_NAME}
      - FYP_SITE_PORT=${FYP_SITE_PORT}
      - FYP_SITE_PROTOCAL=${FYP_SITE_PROTOCAL}
      - FYP_ALLOWED_HOSTS=${FYP_ALLOWED_HOSTS}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - SEND_ACTIVATION_EMAIL=${SEND_ACTIVATION_EMAIL}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
    #restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    image: prashanth45/fyp:backend${FYP_VERSION}
    command: pipenv run celery -A fyp worker --loglevel=info
    depends_on:
      - redis

volumes:
  mysql_data:
  redis_data: