version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: prashanth45/fyp:frontendv1
    ports:
      - "80:80"
    environment:
      - FYP_SITE_NAME=${FYP_SITE_NAME}
      - FYP_BACKEND_HOST=${FYP_BACKEND_HOST}
    volumes:
      # - /home/prashanth/FYP/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${MEDIA_PATH}:/app/media

  backend:
    container_name: backend
    build: ./backend
    image: prashanth45/fyp:backendv1
    ports:
      - "8000:8000"
    volumes:
      #- /home/prashanth/FYP/backend/fyp/settings/prod.py:/app/fyp/settings/prod.py
      - ${MEDIA_PATH}:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=fyp.settings.prod
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FYP_SITE_NAME=${FYP_SITE_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: