# Generated by Django 4.2.11 on 2024-05-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='post',
            name='ispublic',
            field=models.BooleanField(default=True),
        ),
    ]
