# Generated by Django 4.2.13 on 2024-05-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_entity_post_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
