# Generated by Django 4.2.13 on 2024-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
