# Generated by Django 4.2.11 on 2024-04-29 17:42

from django.db import migrations, models
import entity.models.Entity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('OTHERS', 'Others')], max_length=100)),
                ('type_name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=entity.models.Entity.custom_upload_to)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
