# Generated by Django 4.2.11 on 2024-05-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entity.models.Entity
import entity.models.Verification


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('OTHERS', 'Others')], max_length=100)),
                ('type_others', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=entity.models.Entity.custom_upload_to)),
                ('ispublic', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='admin_of_entities', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='user_of_entities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('request', models.CharField(choices=[('CREATE', 'Create'), ('JOIN', 'Join')], max_length=100)),
                ('status', models.CharField(choices=[('INVAILD', 'Invalid'), ('SUCCESS', 'Success'), ('PENDING', 'Pending')], default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(fields=('entity', 'user', 'request'), name='only_one_unique_validation'),
        ),
    ]
