# Generated by Django 4.2.13 on 2024-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='maps',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
