# Generated by Django 4.2.11 on 2024-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('INVAILD', 'Invalid')], default='PENDING', max_length=100),
        ),
    ]
