# Generated by Django 4.2.13 on 2024-08-17 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='maps',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='verify_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
