# Generated by Django 4.2.11 on 2024-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('INVAILD', 'Invalid'), ('SUCCESS', 'Success'), ('PENDING', 'Pending')], default='PENDING', max_length=100),
        ),
    ]
