# Generated by Django 4.2.11 on 2024-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_entity_code_alter_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('INVAILD', 'Invalid'), ('PENDING', 'Pending'), ('SUCCESS', 'Success')], default='PENDING', max_length=100),
        ),
    ]
