# Generated by Django 4.2.11 on 2024-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_entity_code_alter_entity_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('INVAILD', 'Invalid')], default='PENDING', max_length=100),
        ),
    ]
