# Generated by Django 4.2.13 on 2024-05-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_alter_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='facebook',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='instagram',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='linkedin',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
