# Generated by Django 4.2.13 on 2024-05-17 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0006_entity_facebook_entity_instagram_entity_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_of_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVAILD', 'Invalid'), ('SUCCESS', 'Success')], default='PENDING', max_length=100),
        ),
    ]
