# Generated by Django 4.2.13 on 2024-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_alter_entity_users_alter_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='type_others',
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('INVAILD', 'Invalid'), ('PENDING', 'Pending'), ('SUCCESS', 'Success')], default='PENDING', max_length=100),
        ),
    ]
