# Generated by Django 4.2.13 on 2024-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_alter_entity_type_alter_entity_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='other_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
