# Generated by Django 4.2.13 on 2024-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_entity_other_type_alter_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Institute', 'Institute'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('INVAILD', 'Invalid'), ('SUCCESS', 'Success'), ('PENDING', 'Pending')], default='PENDING', max_length=100),
        ),
    ]
