# Generated by Django 4.2.13 on 2024-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_alter_entity_type_alter_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('INVAILD', 'Invalid')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
