# Generated by Django 3.2.18 on 2023-04-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.competition'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
