# Generated by Django 3.2.18 on 2023-05-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20230503_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.competition'),
        ),
    ]
