# Generated by Django 3.2.20 on 2023-07-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGETEXT', 'Image and Text'), ('IMAGE', 'Image')], default='IMAGETEXT', max_length=100),
        ),
    ]
