# Generated by Django 3.2.20 on 2023-08-23 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_redeem_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
