# Generated by Django 3.2.20 on 2023-09-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_alter_redeem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='', upload_to='competitions/'),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='status',
            field=models.CharField(choices=[('Q', 'Pending'), ('P', 'Processing'), ('R', 'Redeemed'), ('F', 'Failed')], default='Q', max_length=1),
        ),
    ]
