# Generated by Django 3.2.20 on 2023-09-19 18:33

import categories.models.Competition
from categories.models.Competition import Competition
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20230906_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('COMPETITION', 'Competition')], default='COMPETITION', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='', upload_to=Competition.custom_path),
        ),
        migrations.AddField(
            model_name='competition',
            name='rewards',
            field=models.ManyToManyField(to='categories.Reward'),
        ),
    ]
