# Generated by Django 3.2.20 on 2023-09-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_auto_20230919_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='likes',
            new_name='won_by_likes',
        ),
        migrations.AddField(
            model_name='winner',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.reward'),
        ),
    ]
