# Generated by Django 3.2.20 on 2023-09-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('categories', '0019_auto_20230920_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'Pending'), ('P', 'Processing'), ('R', 'Redeemed'), ('F', 'Failed')], default='Q', max_length=1)),
                ('type', models.CharField(choices=[('UPLOADPOST', 'Upload Post'), ('COMPPARTN', 'Competition Participation'), ('COMPWINNER', 'Competition Winner'), ('SIGNUP', 'SignUp'), ('REDEEM', 'Redeem')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='points',
        ),
        migrations.DeleteModel(
            name='Redeem',
        ),
    ]
