# Generated by Django 3.2.20 on 2023-10-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0020_auto_20230920_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.competition'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.post'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
