# Generated by Django 3.2.20 on 2023-10-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231010_1357'),
        ('categories', '0021_auto_20231009_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rewards',
            field=models.ManyToManyField(to='core.Reward'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.reward'),
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
