# Generated by Django 3.2.20 on 2023-10-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rewards',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='reward',
        ),
        migrations.AddField(
            model_name='competition',
            name='points',
            field=models.CharField(default=(2000, 1500, 1000), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='points',
            field=models.PositiveBigIntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2),
            preserve_default=False,
        ),
    ]
