# Generated by Django 3.2.23 on 2023-12-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0026_auto_20231206_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
