# Generated by Django 3.2.23 on 2023-12-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0028_category_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='key',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
