# Generated by Django 3.2.20 on 2023-10-10 13:57

import core.models.Reward
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='', upload_to=core.models.Reward.custom_upload_to)),
                ('points', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('COMPTN', 'Competition'), ('ZOMATO', 'Zomato'), ('SWIGGY', 'Swiggy'), ('BMS', 'Book My Show'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('MYNTRA', 'Myntra')], max_length=100)),
                ('external', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=250),
        ),
    ]
