# Generated by Django 3.2.20 on 2023-10-10 14:02

import core.models.Reward
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231010_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Reward.custom_upload_to),
        ),
    ]
