# Generated by Django 3.2.20 on 2023-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.CharField(max_length=255),
        ),
    ]
