# Generated by Django 3.2.20 on 2023-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='realvalue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
