# Generated by Django 3.2.20 on 2023-10-14 14:04

import core.models.Reward
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231011_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='realvalue',
            new_name='pointsvalue',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='external',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='position',
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(default='rewards/ZOMATO.png', upload_to=core.models.Reward.custom_upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(default='Zomato', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('ZOMATO', 'Zomato'), ('SWIGGY', 'Swiggy'), ('BMS', 'Book My Show'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('MYNTRA', 'Myntra')], max_length=100),
        ),
    ]
