# Generated by Django 3.2.20 on 2023-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231014_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinactivity',
            name='points',
            field=models.IntegerField(),
        ),
    ]
