# Generated by Django 3.2.20 on 2023-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coinactivity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinactivity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinactivity',
            name='type',
            field=models.CharField(choices=[('PARTN', 'Participation'), ('COMPPARTN', 'Competition Participation'), ('COMPWINNER', 'Competition Winner'), ('SIGNUP', 'SignUp'), ('REDEEM', 'Redeem')], max_length=100),
        ),
    ]
