# Generated by Django 3.2.20 on 2023-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20231031_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('REWARD', 'Reward')], max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
    ]
